name: Hugo

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [0.71.0, 0.72.0, ""]
        image: [busybox, alpine, ext-alpine, ext-debian, ext-ubuntu]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
