name: Hugo

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [0.56.3, 0.57.2, ]
        image: [busybox, alpine, alpine-ext, debian-ext, ubuntu-ext]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
