name: github pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ '10', '11', '12', '13', '14' ]
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Build
        run: npm install &&
             npm --version &&
             npm install -g postcss-cli &&
             npm install autoprefixer &&
             npm audit fix &&
             hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}
          external_repository: Printed-Robots/Printed-Robots.github.io
          publish_branch: master

