name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          extended: true

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm --version 
      - run: npm install -g postcss-cli
      - run: npm install autoprefixer
      - run: npm audit fix

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}
          external_repository: Printed-Robots/Printed-Robots.github.io
          publish_branch: master

