name: Publish Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [0.72.0]
        image: [ext-alpine]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 1         # Fetch all history for .GitInfo and .Lastmod

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        full_commit_message: ${{ github.event.head_commit.message }}
        external_repository: Printed-Robots/Printed-Robots.github.io
        publish_branch: master
